### PR TITLE
Latest json pr review

### PR DESCRIPTION
**Pull request by bskinn**
Merge changes from Apr 2021 @ewjoachim reviews.

### CODE REVIEW

**Comment by ewjoachim** [comment]
(I'm not sure if you expect me to review this PR or if we continue the work on the main PR)
(Very nice work, btw)

**Comment by bskinn** [comment]
@ewjoachim Thanks!

I thought that setting it up this way might provide cleaner diffs, with this PR showing just the changes I'd made per your reviews. Not sure if it's a standard workflow or not.

In any event, I don't have a preference for whether review happens here or back on the main PR... I could see it making more sense to have the review on the main PR, though, so that all the review is collected in one place. If you agree, I'll go ahead and just merge this PR so that the changes propagate back to pypa#8615.

**Comment by ewjoachim** [comment]
No problem, let's do that on the main PR.

A few "classical" ways to solve this:
- Push additional commits to the main PR, given one can review commit by commit and GitHub will even tell you which commits are new since your review. If you want to be very explicit, add a comment in the PR stating the name of the first commit to review.
- If you really want a clean history, you can create "fixup commits" with `git commit --fixup <commit hash>` so that you can push them now, and once they've been reviewed, you can automatically clean your history with `git rebase --autosquash upstream/main`. Note that, on Warehouse, spending time cleaning the history is not necessarily useful given the maintaniers usually squash and merge, so all commits get squashed into a single one.

So all in all, don't bother too much, stacking git commits in a single PR is usually enough even when there are multiple rounds of review.

**Comment by bskinn** [comment]
Ahh, I hadn't fully realized how `--fixup` and `--autosquash` worked together -- cool! Definitely will be useful in some situations; and, I agree, definitely limited utility there for projects with a squash-merge PR policy. 👍

**Pull request merged**
